### ISSUE TITLE
enable inheriting of `clippy.toml`

### ISSUE THREAD

**Issue by oli-obk** [Manishearth/rust-clippy#1295]
add a field to `clippy.toml` that allows it to refer to a git repository or a path where a `clippy.toml` is located. Pre-initialize all settings from the referred `clippy.toml` and then overwrite with the local `clippy.toml`.

Open questions:

*   how to cache the downloaded `clippy.toml`
*   is the referred `clippy.toml` allowed to refer to others itself?

**Comment by shepmaster** [comment]
Here's my *ideal* world:

**Cargo.toml**

```toml
[dev-dependencies]
clippy = "1.0.0"
clippy-integer32-preset = "2.1.8"
clippy-shepmaster-preset = "0.55.3"
```

**clippy.toml**

```toml
inherit-from = ["integer32", "shepmaster"]

# project-specific-settings
```
