### ISSUE TITLE
README lists two options of including clippy, and an open question

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#225]
The README contains:

    To use, add the following lines to your Cargo.toml:

    ```
    [dependencies]
    clippy = "*"
    ```
as well as (a bit below):

    Add in your `Cargo.toml`:
    ```toml
    [dependencies.clippy]
    git = "https://github.com/Manishearth/rust-clippy"
    ```

I think we should keep the latter for now. @Manishearth what do you think?

Also I think it *should* be possible to include clippy under `[dev-dependencies]`. However, I don't know how we should make the `#![plugin(clippy)]` only relevant for release.
